# Introduction to Tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check number of dimensions
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check dimensions of our vector
vector.ndim

1

In [7]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[10.,7.],[3.,2.],[8.,9.],
                      [11.,4.],[24.,1.],[3.,4.]]], dtype= tf.float16)
tensor

<tf.Tensor: shape=(1, 6, 2), dtype=float16, numpy=
array([[[10.,  7.],
        [ 3.,  2.],
        [ 8.,  9.],
        [11.,  4.],
        [24.,  1.],
        [ 3.,  4.]]], dtype=float16)>

In [12]:
tensor.ndim

3

### Creating tensors with tf.variable

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
unchangeable_tensor, changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#changeable_tensor[0] = 10    # -> gets error

In [15]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# unchangeable_tensor[0] = 7
# unchangeable_tensor[0].assign(7)

#Both get error because it is a constant tensor.

### Creating random tensors

In [17]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
# Are they equal?

random_1 , random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling a tensor

In [19]:
not_shuffled = tf.constant([[10,7],[3,4],[2,6]])
print(not_shuffled.ndim)
not_shuffled

2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  6]], dtype=int32)>

In [20]:
tf.random.shuffle(value=not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  6]], dtype=int32)>

In [21]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 100)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  6],
       [ 3,  4],
       [10,  7]], dtype=int32)>

### Other ways to make tensors

In [22]:
#Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
#Create a tensor of all zeroes

tf.zeros(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [24]:
# Turn numpy arrays into tensors:

import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [26]:
# Create a rank 4 tensor:

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Indexing Tensors

In [30]:
# Indexing the first two elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0,0,0,:], rank_4_tensor[:1,:1,:1,]

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>)

In [32]:
# Create a rank 2 tensor

rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [33]:
# Get the last item of each row of our rank 2 tensor

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [34]:
# Add in an extra dimension

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [35]:
# Alternative way to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand on the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors: Tensors Operations

#### Basic Operations

In [37]:
# Add Values to a tensor using the addition operator

tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [38]:
# Multiply, Substraction, Division
print(tensor * 10)
print(tensor - 10)
print(tensor / 10)

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


In [39]:
# We can also use the tensorflow built in function

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication (tensors multiplication)

In [40]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [41]:
# Element wise:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [42]:
#Matrix multiplication with tensorflow function
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
# Matrix multiplication with python

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
X = tf.constant([[1,2],
                [3,4],
                [5,6]])

Y = tf.constant([[7,8],
                [9,10],
                [11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [45]:
# since the last two matrices are the same dimensions we cannot do dot product. For this we need the inner dimensions of both matrices 
# (or tensors) to be the same. So we need to reshape one of them.

tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [46]:
# Now multiply again:

# tf.matmul(X,Y)  # Gives error cause the inner dimensions don't match.

In [47]:
# Transpose is a bit different.

X, tf.reshape(X, shape = (2,3)), tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [48]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Changing the datatype of the tensor

In [49]:
B = tf.constant([1.7, 7.4])
C = tf.constant([7,10])


B.dtype, C.dtype

(tf.float32, tf.int32)

In [50]:
# Change from float32 to float16 (reduced precision)

D = tf.cast(B, dtype= tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregating tensors

In [51]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [52]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#### Let's do some aggregations

In [53]:
# First lets create a random tensor

E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([34,  7, 37, 84, 37, 29, 88, 69, 84, 47, 19, 56, 54, 26, 88,  0, 87,
       84, 82, 27, 57, 49,  8, 99,  5, 28, 29, 38, 51, 27, 33, 71, 42, 13,
       86, 78, 62, 30, 69, 61, 16,  9, 52, 53, 74, 22, 90, 79, 56, 34])>

In [54]:
#Finding minimum

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [55]:
#Finding maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [56]:
# Finding mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [57]:
# Finding the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2460>

In [65]:
# Finding variance and standard deviation

tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=732.8>

In [66]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.070278>

### Find the positional maximum and minimum

In [74]:
# Create a new tensor
tf.random.set_seed = 42
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.43555546, 0.52486527, 0.49674678, 0.06710219, 0.35815144,
       0.5931845 , 0.8396933 , 0.32720697, 0.08762932, 0.0971967 ,
       0.9376564 , 0.18501604, 0.9981525 , 0.82236457, 0.42403674,
       0.05161929, 0.20221865, 0.8313112 , 0.02180374, 0.7716117 ,
       0.43708587, 0.38407493, 0.8155345 , 0.8697617 , 0.1877197 ,
       0.6120846 , 0.01730704, 0.6251298 , 0.9047519 , 0.45837843,
       0.98503745, 0.39521003, 0.4194014 , 0.2234962 , 0.9076545 ,
       0.13453591, 0.3705256 , 0.84200656, 0.86062145, 0.06019282,
       0.2456857 , 0.9456284 , 0.6033411 , 0.66060483, 0.43036914,
       0.7185979 , 0.49352026, 0.1214813 , 0.7401178 , 0.09666443],
      dtype=float32)>

In [76]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [77]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9981525>

In [78]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9981525>

In [83]:
#Check for equality

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [85]:
# Find the positional minimum

tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=26>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.017307043>)

### Squeezing a tensor

#### Removing all single dimensions

In [88]:
tf.random.set_seed = 42
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[1.27802730e-01, 8.62301230e-01, 4.15632963e-01,
           1.00286722e-01, 6.07836485e-01, 7.90521741e-01,
           6.06833696e-02, 8.56746435e-01, 7.20012665e-01,
           6.80043340e-01, 3.18007350e-01, 9.15518522e-01,
           9.83233213e-01, 9.49099660e-01, 9.27690983e-01,
           4.26432252e-01, 1.65649414e-01, 5.96877337e-02,
           1.01531982e-01, 3.48368764e-01, 1.06096268e-05,
           5.53984642e-01, 1.04559660e-02, 1.70157075e-01,
           5.35020947e-01, 3.53641510e-02, 5.11248112e-02,
           3.47512603e-01, 4.17755604e-01, 4.66669559e-01,
           9.22843099e-01, 6.48598909e-01, 3.84631276e-01,
           7.53028631e-01, 9.17651892e-01, 5.70779085e-01,
           9.69477892e-02, 4.58525062e-01, 2.72809863e-01,
           7.18811393e-01, 6.84959650e-01, 9.46360826e-01,
           6.96492195e-02, 1.22516274e-01, 5.67929626e-01,
           6.14467025e-01, 2.55180240e-01, 7.69669652e-01

In [89]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [90]:
G_squeezed = tf.squeeze(G)
G_squeezed,  G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([1.27802730e-01, 8.62301230e-01, 4.15632963e-01, 1.00286722e-01,
        6.07836485e-01, 7.90521741e-01, 6.06833696e-02, 8.56746435e-01,
        7.20012665e-01, 6.80043340e-01, 3.18007350e-01, 9.15518522e-01,
        9.83233213e-01, 9.49099660e-01, 9.27690983e-01, 4.26432252e-01,
        1.65649414e-01, 5.96877337e-02, 1.01531982e-01, 3.48368764e-01,
        1.06096268e-05, 5.53984642e-01, 1.04559660e-02, 1.70157075e-01,
        5.35020947e-01, 3.53641510e-02, 5.11248112e-02, 3.47512603e-01,
        4.17755604e-01, 4.66669559e-01, 9.22843099e-01, 6.48598909e-01,
        3.84631276e-01, 7.53028631e-01, 9.17651892e-01, 5.70779085e-01,
        9.69477892e-02, 4.58525062e-01, 2.72809863e-01, 7.18811393e-01,
        6.84959650e-01, 9.46360826e-01, 6.96492195e-02, 1.22516274e-01,
        5.67929626e-01, 6.14467025e-01, 2.55180240e-01, 7.69669652e-01,
        3.94763947e-01, 6.69542074e-01], dtype=float32)>,
 TensorShape([50]))

### One hot encode

In [95]:
some_list = [0,1,2,3]

tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, log, square root

In [97]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [98]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [101]:
tf.math.sqrt(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [104]:
tf.math.log(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [108]:
#Create a tensor from a numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [109]:
#Convert back to numpy array
np.array(J)

array([ 3.,  7., 10.])

In [110]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU

In [3]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
import tensorflow as tf
devices = tf.config.list_physical_devices()
print("\nDevices: ", devices)

gpus = tf.config.list_physical_devices('GPU')
if gpus:
  details = tf.config.experimental.get_device_details(gpus[0])
  print("GPU details: ", details)


Devices:  [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
GPU details:  {'device_name': 'METAL'}


In [5]:
# import tensorflow as tf

# cifar = tf.keras.datasets.cifar100
# (x_train, y_train), (x_test, y_test) = cifar.load_data()
# model = tf.keras.applications.ResNet50(
#     include_top=True,
#     weights=None,
#     input_shape=(32, 32, 3),
#     classes=100,)

# loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)
# model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])
# model.fit(x_train, y_train, epochs=5, batch_size=64)